### ISSUE TITLE
Question Anwser And Questions

### ISSUE THREAD

**Issue by mpegyna** [mjp66/Ubiquiti#11]
Hi, many thanks for your most detailed guide. I firstly got version from October from a random google search on a random website. I spent some time upgrading and basic setting of my router and now I found your source and updated version!

Before I ask some questions I have an answer to your question in chapter 22. 'How do you restore using the ISP’s resolvers?' I had to figure it out, because other DNS was causing me some troubles and it seems that my ISP DNS is better for now. CLI commands are following (for eth0 as ISP connection):
```
configure
delete service dns forwarding system
set service dns forwarding listen-on eth0
commit
save
exit
```

My main question is for your Home Network (192.168.3.X). You have almost no dedicated part for that. Does it mean that the setting (for DHCP and such) is done mainly by the initial Wizard setting and then you modify a thing here and there while configuring other networks? I have situation with only one LAN and no secure wired network or wired IOT network and I'll be using two Unify UAP-LR access points. So I'm mainly interested in more WiFi Networks and only one LAN setting. I've stopped at DHCP setting, because I don't know if I stay with Wizard setting or I edit it somehow like you in chapter 18. for eth2?

And the other question is dnsmasq vs ISC. In your October version the dnsmasq was bugged and your only choice was ISC. What is the situation now and what is better to use?

Thank you!
mpeg.

**Comment by mjp66** [comment]
All references are to the 1/21/2018 version of the guide.

> My main question is for your Home Network (192.168.3.X). You have almost no dedicated part for that. Does it mean that the setting (for DHCP and such) is done mainly by the initial Wizard setting and then you modify a thing here and there while configuring other networks?

That is correct.

> I have situation with only one LAN and no secure wired network or wired IOT network and I'll be using two Unify UAP-LR access points. So I'm mainly interested in more WiFi Networks and only one LAN setting.  I've stopped at DHCP setting, because I don't know if I stay with Wizard setting or I edit it somehow like you in chapter 18. for eth2? 

The following directions are only approximate.
You can alternately choose HomeNet on ports 1,3,4 or 2,3,4 or 1,2,3,4.
You will be giving up features.
To include port 1 in HomeNet, instead CHECK the "One LAN" box in section 10 / Figure 21.
You will need to figure out the later associated changes.
To include port 2 in HomeNet, DON'T follow sections 17, 18.
You will need to figure out the later associated changes. An example is section 23.

For using two UAPs, reference section 12, and (new) bottom of section 26.
Since you will have 1 or 2 "extra" HomeNet router ports, you should be able to plug the second UAP directly into the router. This saves needing to buy and setup an 802.1Q managed switch.
Note that the two UAPs should be setup the same (but each using different non-overlapping channels)
and would provide more coverage area. An example would be positioning at different ends of a house.
OR the two UAPs and ER-X could be setup with more VLANS and thereby provide more SSIDs.
I would look at [https://community.ubnt.com/t5/UniFi-Wireless/bd-p/UniFi](https://community.ubnt.com/t5/UniFi-Wireless/bd-p/UniFi) for more info on UAP setup.
See also the (new) VLAN data under the Question in section 26.

> And the other question is dnsmasq vs ISC. In your October version the dnsmasq was bugged and your only choice was ISC. What is the situation now and what is better to use?

dnsmasc. See sections 19, and (new/updated) section 20, 
It is likely that my settings for dnsmaqs are not yet optimized or entirely correct.
But it seems to work.

Get in there and try different things / experiment.
That's how I put the guide together, I'm not a network engineer.
You would do well to keep multiple backups, as you experiment.

Hope this helps,
-Mike

**Comment by dmaroulidis** [comment]
Hi,
I am using the exact setup in the guide, and I tried setting the guest portal for the Wi-Fi Guest Network, and any guest connected to the Network, doesn't see the portal, and cannot access the Internet. The controller is located in the Home Net.

I've tried adding firewall rules to allow access to 192.168.3.10 (the controller's IP) from the WiFi Guest Net, but to no avail.

Any idea?

**Comment by mjp66** [comment]
@dmaroulidis I don't remember any address of 192.168.3.10 being used in the guide.
The only feedback on the UAP setup was in: Issues https://github.com/mjp66/Ubiquiti/issues/7
Sorry, I probably will not be able to help you. Just keep trying, one of us probably has a typo. 
-Mike

**Comment by mjp66** [comment]
Portions added to guide.
