### ISSUE TITLE
Using Quad9 and dnsmasq

### ISSUE THREAD

**Issue by wallyboy53** [mjp66/Ubiquiti#17]
Mike,
thanks  for this guide, it made a big difference for me getting started with the erx.
thanks for keeping grc updated on your doings, it was how I found this guide.
Two queries, one quad 9 related.
On quad 9 setup, using dnsmasq, there is a section where you use the cli to allow local hostname resolution. Having done that, my system nameserver is, in order, 127.0.0.1, 9.9.9.9, 149.112.112.112.  
I am hoping that is as it should be...  Also not sure I've discerned the correct instructions for setting the dns forwarding, currently I am showing a forwarding list of switch0... that differs with the previous version of your setup where eth1, switch0, eth2... again hoping I've understood as you intended

Another enhancement that I have not succeeded in, is sorting out bonjour broadcasts for enabling my appleprint and appleplay stuff... I would like to keep the internet connections of my players and printers on either the wired or wireless iot nets, but bonjour, I am reading, does not cross subnets... there is a lot of discussion about using the mdns repeater service, where I think I am failing is sorting out the rules in this setup for allowing the multicasts to be accepted by the subnets without blowing open holes I'd rather not ... any insights or help you can offer would be appreciated

**Comment by mjp66** [comment]
If you can connect from one PC on your Home Network to another PC on your Home Network by referencing its name, i.e. by typing (example) "ping DifferentPcName" or "http://DifferentPcName",  etc.... then your local hostname resolution is working.

I have not looked into mdns / bonjour. Maybe you could look up bridging. The EdgeMax community usually advises against it,  as it can overload the router's cpu / slow down network traffic. Another possibility is to put all of your stuff on just the Wifi Iot network.

I would think the Apple items you mentioned, would reside on the Home Network, since they should be getting updates.

-Mike

**Comment by mjp66** [comment]
See new section 73 in guide.
