### ISSUE TITLE
Define IoT Devices

### ISSUE THREAD

**Issue by MikeWills** [mjp66/Ubiquiti#18]
I got my EdgeRouter X all configured last night and my UAC-LITE will be here tomorrow. My open question is the definition of IoT devices. What would that all include? Might be worth including for documentation sake.

**Comment by miquelfire** [comment]
Based on the name, IoT would be those "smart" light bulbs and things like it.

The way I'm using it if a device may not be getting upgrades anymore or soon (its End of Life is near) or I just can't tell if it's secure enough to not have a hack do something to my main computer, I put it on the IoT network. If it's Chomecast related, it goes there as well.

**Comment by MikeWills** [comment]
And I know about the lights bulbs, thermostats, dryers, ovens, fridges, and stuff like that. My question go towards printers, Rokus, Chromecast, Fire Sticks, and other things where there is direct communication between phones/PCs and the device. Or is that why communication is allowed from home to IoT, but not the other way.

**Comment by MikeWills** [comment]
Also, is there a level of complications associated with the separation for the non-techies.

**Comment by miquelfire** [comment]
Side note, when I said Chromecast related, I include phones and tablets. I don't know what Roku and Fire Stick do to require a direct communication from devices so I can't say anything about them, but I do know that Chromecast's API requirements to work needs everything to be on the same subnet to work without issues. Also, the guest and LAN broadcast checkboxes need to be turned off because they block whatever data is needed to allow those devices to work.

Also, I have my printer on my main subnet. Basically, if you don't have a way to set an IP on the client side to connect to a device when there's no cloud server acting as a go-between, they need to be on the same subnet. Basically, it's really up to you.

**Comment by patrickn** [comment]
The default firewall rules are such that requests originating on the home subnet do reach the IOT subnet. My WiFi printer is on the IOT subnet on (192.168.7.x), I connect to it from my home subnet (192.168.3.x).

**Comment by mjp66** [comment]
@miquelfire  said it very well: 
>  The way I'm using it if a device may not be getting upgrades anymore or soon (its End of Life is near) or I just can't tell if it's secure enough to not have a hack do something to my main computer, I put it on the IoT network. 

Some devices could go either on the Home Network or Iot Network. I'll use an Amazon Echo as this example. The echo typically uses a smart phone app to control it. Since Amazon's phone app doesn't have a place to enter the echo's IP address, then both the phone and the echo need to be on the same Network. If you want the echo to live on the Iot network, then you will need to temporarily switch networks / connect your phone to the Iot Network to control the echo. Since the echo gets regular updates from Amazon, I don't see having this device on the Home Network as a real problem.

Some devices I would NOT let on my Home Network, i.e. Baby Monitors / Security Cameras / etc... Most of these devices ultimately come from Chinese manufacturers. Who knows what they are doing inside their firmware. Are there hard coded passwords / open telnet ports / etc... Who knows? To me they are not worth the risk of having them on the Home Network. 

This is ultimately a convenience vs security trade off. Choose carefully. With the flexibility you get with the ER-X, at least you now HAVE an Iot network, where you can choose were to put your stuff.

-Mike
