### ISSUE TITLE
UPnP for Google Home

### ISSUE THREAD

**Issue by Scott216** [mjp66/Ubiquiti#27]
I've got a Google Home Mini and some chromecast devices.  Google says I need to enable UPnP.  I know UPnP is better left off for security reasons, but I don't know what firewall rules Google would need.  To turn UPnP on, I assume external interface is eth0, but what should I use for the internal interface?

**Comment by miquelfire** [comment]
I have those devices and I haven't turned on UPnP, and they work just fine for me.

**Comment by Scott216** [comment]
When I switched over to my EdgeRouterX and UniFi A/P, my WiFi SSID was different.  I wasn't able to re-setup any of the Google devices (Home, Chromecast).  So I changed the SSID to the old one (same password too), and the Google devices worked again.  I wonder if Google Home/Chromecast needs UPnP for setup only. I guess I'll find out next time I get another device.

**Comment by jeclark15** [comment]
Hey @Scott216 I'm not sure if this will help, but I'll put it out there. I recently helped family set up an ERX and AP who had trouble getting their Google Nest Detects to work. After a fair amount of troubleshooting, it turned out to be the google devices wanting to use multicast during initial configuration. Since the IoT network was set up as a "guest" network for isolation, it blocked such traffic. They disabled that in the AP and all was good during initial setup, and after turning it back on, they continued to work. 
Not the same device you're dealing with, but maybe it's doing the same thing? Hope this helps.

**Comment by mjp66** [comment]
Sorry @Scott216, but I have never setup UPnP on any router. That is why I left that section blank in the guide.  Most of my research for this guide came from the [EdgeRouter Community Forum](https://community.ubnt.com/t5/EdgeRouter/bd-p/EdgeMAX) as also stated in Issue #28 by @rmoorewrs. You will just need to research this on your own, as there are hundreds of UPnP links in the forum.

**Comment by Scott216** [comment]
Thanks Mike.  Good to know.
