### ISSUE TITLE
Quad 9 Replacement with 1.1.1.1

### ISSUE THREAD

**Issue by sengsational** [mjp66/Ubiquiti#34]
Using Steve Gibson's DNS Benchmark shows a rather slow DNS result when the EdgerouterX is configured as in the PDF.  I learned quite a bit going through the PDF, so I can probably just reconfigure this myself, but I thought I'd mention it here, since there might be a change offered in the next revision of the PDF.

[https://i.stack.imgur.com/UUzza.jpg]DNS Benchmark showing 9.9.9.9 is slow and 192.168.3.1 is slow.

**Comment by mjp66** [comment]
Hi,

I just ran the benchmark and Quad9 was slower for me also. You will have to make a security vs speed trade off for yourself. I will probably add something similar to the following in "Section 20 - About DNS Settings" the next time I update the guide:

"Some people are reporting that Quad9 is slower, See Section 73 - Adblocking and Blacklisting as a possible security alternative."

Thanks,
-Mike

**Comment by GeoffWy** [comment]
@sengsational  I too find Quad9 a little slower but I wonder if it matters that much since you would be hoping for most lookups to come from your router's cache which is extremely fast. Also I wonder if you have some problem in your setup or with your service as you seem to have a lot of failures on most of your dns servers. You don't give the scale so its hard to tell just how bad it is. My own dns benchmark is here [DNSbenchmark.png](https://github.com/GeoffWy/DNS-performance/blob/master/DNSbenchmark.png). Full scale is 100ms (20ms/div).
I have set my dns addresses in the dns service with dns forwarding to system disabled and no addresses set in system. 

I have just posted on the forum about dns forwarding settings [Making-sense-of-DNS-forwarding-options](https://community.ubnt.com/t5/EdgeRouter/Making-sense-of-DNS-forwarding-options/m-p/2590993#M231673), which you may find of interest @mjp66 .

Regards
Geoff
