### ISSUE TITLE
Question to guide 56. WIRED_IOT_LOCAL - Rule 1 (Allow DHCP)

### ISSUE THREAD

**Issue by madsthygesen** [mjp66/Ubiquiti#42]
Hi Mike - Thanks for all of your efforts in creating this guide.

I am trying to setup an edgerouter 10X with your guide, but I am stuck at 56. WIRED_IOT_LOCAL - Rule 1 - Allow DHCP

What should I put for source?

name WIRED_IOT_LOCAL {
default-action drop
description "Wired Iot Local"
rule 1 {
action accept
description "Allow DHCP"
destination {
port 67-68
}
log disable
protocol udp
source {
}
}
![image](https://user-images.githubusercontent.com/54471860/63636711-18bba480-c673-11e9-8909-30c71ea315da.png)

Thank you very much.

**Comment by GeoffWy** [comment]
Source should be port 68, Destination port 67

**Comment by madsthygesen** [comment]
OK, but why does it state destination {67-68}, and source empty? (It actually works with source empty at the moment, jut finished with the guide).

Thank you for your time :)

**Comment by GeoffWy** [comment]
I guess its a mistake, as you say it will work as you configured it.
A DHCP server uses port 67 and the client uses port 68.
There is no need to have port 68 as a destination, since there will never be a DHCP server amongst the IOT serving a LOCAL service.
You don't have to put port 68 in the source but it locks it down a bit more to do so as nothing should be talking to the DHCP server using any other port.

**Comment by madsthygesen** [comment]
Thanks for the explanation, I will correct the setup, so destination = port 67 and source = port 68.

Have a nice weekend :)

**Comment by mjp66** [comment]
Thanks guys, I'll look into this the next time I do a document update.

**Comment by madsthygesen** [comment]
Thanks Mike, I successfully setup up an ER-10X on firmware v. 2.0.6 and a UAP-nanoHD, with your guide.
