### ISSUE TITLE
No info on address groups

### ISSUE THREAD

**Issue by vildasha** [mjp66/Ubiquiti#43]
I cannot find any mentions on NETv4_switch0.7 address group as well as NETv4_switch0.6, NETv4_switch0.7, NETv4_switch0.8

**Comment by mjp66** [comment]
In the last release of the guide, I switched from using Address Groups to Interface Networks. Look at all of page 75. There is also a link to investigate on that page.  Interface networks seemed to involve less setup, and therefore seemed to be less messy than real address groups. Also reference Figure 100.

I had not noticed, but it looks like Ubiquiti calls multiple items "address-group" in the config.boot / backup file instead of something unique / different / more descriptive. I would have preferred a more friendly name, like, "interface-network".

In the GUI, try choosing Interface Network for the items you mentioned. I can add more text describing this issue in the next release of the guide.  Hope this is what you needed and that this helps you.

-Mike
