### ISSUE TITLE
Add mDNS port to VLAN LOCAL rulesets

### ISSUE THREAD

**Issue by geckofish** [mjp66/Ubiquiti#47]
I followed your guide, but was having an issue with the mDNS repeater not working.  I found that I had to add the UDP destination port 5353 to the VLAN LOCAL rulesets.

**Comment by mjp66** [comment]
Ok. Sounds like a Chromecast. If so, I don’t own one.

**Comment by GeoffWy** [comment]
mDNS is used by a whole range of things including Apple Bonjour service, Windows 10 printer discovery, etc, not just Chromecasts. mDNS messages are multicast UDP packets to port 5353. Multicasts are normally limited to a single subnet, but operation can be extended to other subnets using the mDNS repeater. As the mDNS repeater is a service in the router you have to unblock messages to port 5353 in the "to LOCAL" firewall rules, otherwise they will never reach the repeater. That will probably apply to guest and iot subnets where the default is to block access to LOCAL.
There is an overview of mDNS here [https://en.wikipedia.org/wiki/Multicast_DNS](url)
If you have devices on wireless subnets you might also need to play with unblocking LAN to WLAN Multicast data in Unifi/Wireless Networks/Advanced options. You shouldn't have to as messages from the gateway (ie edgerouter) to WLAN are enabled automatically.
