### ISSUE TITLE
Answer to a question

### ISSUE THREAD

**Issue by badabing2005** [mjp66/Ubiquiti#5]
First of all, great document, it's truly well structured and in great detail, kudos.

I'm still going through the document and came across the following question on page 32.

> When writing this guide, I was not able to figure out how to combine the Wired IOT Network (as 192.168.4.X) and
> the Wi-Fi IOT Network (as 192.168.7.X) as a single Network / Subnet.
> QUESTION: Is there a way to combine these two Networks / Subnets?

Take a look at this video
https://www.youtube.com/watch?v=kl9CkHhLm6k&index=23&list=WL
Basically all you have to do is set a pvid 6 to ETH1 and not configure ETH1 Address Manually.
It's supposed to be faster as well, as it does hardware switching instead of software switching.

Let us know if you see an issue with this approach.

**Comment by miquelfire** [comment]
My Edgerouter X is coming today (I already got the access point, the router was on backorder), so I should have time to test this out over the weekend.

**Comment by mjp66** [comment]
Thanks, I'll try to look into this also.

**Comment by miquelfire** [comment]
Okay, here's the changes that I have made (As of now, I have only moved two devices, and they're both on the IOT network, one of them only because it's not getting patched any more, but it allowed me to test if the separation worked or not on the different networks):

* I swapped the roles of eth1 and eth2
* After doing the wizard, I plugged my setup computer in eth1 as the main change here will have you lose access to the 3 subnet for a bit
* Create a VLAN 1 on switch0
* Configure switch0 to not have an IP, and under the VLAN tab
  * eth2 pvid set pvid to 7 (IOT VLAN)
  * eth3 and eth4 set pvid to 1
  * eth4 vid as 6,7 while we're here
* Assign VLAN 1 to the 3 subnet
* At this point, go to services, DNS, and add the switch0.1 as a listening interface. This way, the setup computer and the home network can make DNS requests. (Need to do this for VLANs 6 and 7 once created for those who are using the Edgerouter X as the DNS servers for those subnets, I don't remember seeing anything about it in the guide)

**Comment by mjp66** [comment]
See comments in section 26.
