### ISSUE TITLE
IPV6?

### ISSUE THREAD

**Issue by kd5byb** [mjp66/Ubiquiti#62]
Greetings!  Just got a Starlink setup and hoping there might be an update the excellent directions you've put forward to cover enabling IPV6 on the ER-X?

thanks!
-ben

**Comment by mjp66** [comment]
Sorry, No, as I have no IPV6 equipment.

You might want to search the Edge Max topics, i.e.:
https://community.ui.com/tags/edgemax/questions?page=1
Maybe sort by "Activity".  You can also enter keywords, for example: starlink.

For an example from the above search, see this BuckeyeNet posting:
https://community.ui.com/questions/Gateway-target-0-0-0-0-and-not-routing-packets/8576234c-5d61-4ef7-81e0-27ac5b07d7e1#answer/72ffb909-1ab4-43c3-b210-fc110eb3418b

Good Luck,
-Mike

**Comment by edwardsmarkf** [comment]
Mike, I am tempted to send you the latest model as a motivation to try it out & report back. 😎

But I did want to try out the eight-port model,but was hoping you tried it first.

On April 24, 2022, at 5:41 PM, Mike ***@***.***> wrote:

Sorry, No, as I have no IPV6 equipment.

You might want to search the Edge Max topics, i.e.:
https://community.ui.com/tags/edgemax/questions?page=1
Maybe sort by "Activity". You can also enter keywords, for example: starlink.

For an example from the above search, see this BuckeyeNet posting:
https://community.ui.com/questions/Gateway-target-0-0-0-0-and-not-routing-packets/8576234c-5d61-4ef7-81e0-27ac5b07d7e1#answer/72ffb909-1ab4-43c3-b210-fc110eb3418b

Good Luck,
-Mike

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you are subscribed to this thread.￼Message ID: ***@***.***>

[ { ***@***.***": "<a href="http://schema.org">http://schema.org</a>", ***@***.***": "EmailMessage", "potentialAction": { ***@***.***": "ViewAction", "target": "<a href="https://github.com/mjp66/Ubiquiti/issues/62#issuecomment-1107954154">https://github.com/mjp66/Ubiquiti/issues/62#issuecomment-1107954154</a>", "url": "<a href="https://github.com/mjp66/Ubiquiti/issues/62#issuecomment-1107954154">https://github.com/mjp66/Ubiquiti/issues/62#issuecomment-1107954154</a>", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { ***@***.***": "Organization", "name": "GitHub", "url": "<a href="https://github.com">https://github.com</a>" } } ]
