### ISSUE TITLE
you forgot to add  vlan setup in the unifi controller

### ISSUE THREAD

**Issue by apilon59** [mjp66/Ubiquiti#64]
Love your guide but you forgot one important step. You need to create a network  that is vlan only for vlan 6,7, and 8 and then when you create the wireless network assign the vlan to them. Same goes when you describe how to merge eth 1 and 4 together

**Comment by mjp66** [comment]
You will need to provide more detailed information than that, as I don't understand what you are asking.

Since your tile says: "you forgot to add vlan setup in the unifi controller"
Maybe see the following text, from page 124 of the 6/3/2022 revision:

You can change the following settings as suites you. Change / Enter the following information:
Name/SSID       GuestWifi
Security           WPA Personal
Security Key    <Enter your own password for the guest Wi-Fi network >
Guest Policy     CHECKED     Apply guest policies
Multicast ...      CHECKED     Block LAN to WLAN Multicast ... Data
VLAN              CHECKED     Use VLAN 6
WPA Mode     WPA2 Only   Encryption AES/CCMP Only
User Group      GuestGroup

Similarly, pages 125 and 126 for VLANS 7 and 8 of the unifi controller.

I also cant make sense of your statement:  "Same goes when you describe how to merge eth 1 and 4 together".

Sorry,
-Mike

**Comment by apilon59** [comment]
Hi, So sorry indeed my comment was not clear at all. Ok let's start over. What i meant is once you created your vlan in the edgerouter -x, you need to go to Unifi controller and set up the same VLAN in UniFi as you did  in the EdgeRouter.

so you go to settings in Unifi 

Click on Network and create new network
Enter the name  “IOT”
Enter VLAN ID 7
and save. 

Then you would go to wireless network to create the new wireless network selecting IOT as vlan.  I do not recall seing this step in your guide. 

as for step 90 Coalescing the wireless IOT and Wired IOT network. I followed your instruction but then when i was finished ETH2 could not resolved an IP Address and homenet bot wired and wireless  had the same problem. not sure why.

**Comment by mjp66** [comment]
Hi,

I think that the user interface has drastically changed over the **five** years that I have been working on this guide.

Reference Figure 150 in the guide, where there is a "use vlan 6" checkbox within the **Wireless Network** section.  That functionality seems to now be moved into the Settings -> Networks section.

Probably something similar to the following is needed for newer UniFi versions:
![networks_step](https://user-images.githubusercontent.com/26348558/177430860-44279397-bf58-493c-a73d-e635cf9e4f73.png)

I have been contemplating (time permitting) re-working the Unifi setup section using a newer / **consistent** version of UniFi.
[We will see IF I can get enough time for this rewrite.]

As to your Coalescing question: maybe you could use a comparison program (I love "Beyond Compare") to difference your own backup ER-X file versus the newest reference-config-file, which is located within (this) GitHub repository. You could always load the reference file into a spare ER-X, to see how that configuration works in your situation.
 
Hope this is what you were asking, and it helps.
-Mike

**Comment by Splitter8** [comment]
Thank you
