### ISSUE TITLE
Add service gui listen-address for 192.168.5.x network

### ISSUE THREAD

**Issue by pawl** [mjp66/Ubiquiti#67]
I had to add 192.168.5.1 as a gui listen-address to allow accessing the edgerouter http/https interface and I didn't see this mentioned in the guide:
![Screenshot from 2023-04-24 21-44-12](https://user-images.githubusercontent.com/992533/234162435-514b86a6-4120-468b-a874-161806b2323a.png)

Note: I didn't use the `WAN+2LAN2` setup, and maybe this was included as part of that.

**Comment by GeoffWy** [comment]
The default setup has no listen address entries, which means the edgerouter
listens on all addresses. You only need to put an address in if you want to
constrain access for improved security in case your login is compromised. I
assume you are accessing the gui at 192.168.5.1, which is why you need to
put that address in. 192.168.1.1 is not active in the Mike Potts setup so
is superfluous.

**Comment by pawl** [comment]
Thanks for the response. Didn't know it listened on all addresses by default.
