### ISSUE TITLE
ER-X / UAP-AC-LR blocking genuine sites

### ISSUE THREAD

**Issue by N3bbish** [mjp66/Ubiquiti#71]
Hi Mike! Over the last three months, I've been experiencing very odd behavior with my ER-X / UAP-AC-LR setup where it is blocking connections to sites like CarFax, NBC.com, Discovery+; even the Roku can't connect to different services. I moved to a new house back in March so I thought it might be due to the ISP, but if I connect a machine directly to the internet, I experience no connectivity problems. In the Unifi Controller, I have disabled Country Restrictions and Threat Management and I've gone through the guide several times to verify my ER-X firewall rules. Everything seems to checkout and I am at a loss. I don't know what I a missing.

To give you an example of what I am seeing, the attached screen capture is what I see when I attempt to log into the CarFax site.
![Capture](https://github.com/mjp66/Ubiquiti/assets/127472248/474f89dc-bc42-430a-be67-ee3b246c6841)

**Comment by mjp66** [comment]
The following items might help you in debugging. Since you say only some web sites are broken, I'm betting on #4.

1. Please ensure that you have not loaded "Adblocking and Blacklisting" as listed in section 69. If loaded, you could temporarily disable it.

2. You have not said if this blockage (only) occurs if connected to Wi-Fi, or if it (also) happens when connected to the ER-X's Ethernet / LAN. I would not connect any equipment (directly) to the Internet without SOME (even a cheap commercial type of) firewall.

3. You have not mentioned what type of service your ISP provides, and/or what WAN equipment your ER-X is connected to. Additionally you have not provided the IP address presented to the ER-X router, i.e. is it a 'real / public' IP address or were you provided Carrier Grade NAT (or equivalent).

4. Even if you don't have PPPoE, you should look at section 79.4 WAN PPPoE Settings, i.e. follow the links and test your own MTU/MSS settings. The Guide state: "Sometimes with PPPoE, your internet may only partially work correctly." Maybe it should instead state: If your MTU/MSS settings don't match you ISP's expectations, ...

5. You have not mentioned how you configured your DNS settings, and/or who is your DNS provider. Under windows you can issue the 'ipconfig /all' command and see what 'DNS Servers' are listed. You can also issue the 'nslookup' command, with a website parameter, e.g. nslookup nbc.com

6. You have not mentioned if you can ping a non-working site. Note: not all sites will honor  ping requests.

Hopefully, this will help you get started debugging.
-Mike

**Comment by N3bbish** [comment]
Hi Mike, thank you for responding.
 1. Adblocking and Blacklisting was never loaded or enabled
 2. The blockage occurs on both wired and wireless devices. I connected a laptop directly to the internet (effectively bypassing my home setup) to prove the problem was coming from my end, not the ISP.
 3.  My neighborhood has community fiber internet supplied by Gigstreem (Gigstreem purchased GigaMonster). The ER-X is connected to a Unifi UF-Nano and has an IP of 24.72.237.160/21. I believe it is a real public IP.
 4. I don't have PPPoE. Based on testing, MTU for me is 1500.
 5. DNS Provider is OpenDNS and configuration matches your guide.
 6. I believe that I misrepresented my problem. I can reach NBC.com, Discovery+, CarFax, etc., but authentication is prevented when I attempt to log in to my account. If I use a VPN, or am outside of my home network, I have no problems logging into accounts.

**Comment by mjp66** [comment]
Hi,

Looks like your IP address is a public address
`IP Address: 24.72.237.160
ASN: 31939
City: McLean
State/Region: Virginia
Country: United States of America
Postal Code: 22102
ISP: GigStreem
Time Zone: -04:00`

I'm out of ideas, maybe someone else here can comment.

If not, the only idea left is to post this question on ubiquiti's community site.
Feel free to mention @mjp66 in the posting and mark EdgeMax as the category.
They will likely request you to post your config file, ensure you redact your username and password before posting, and put it in a code tag.

Good Luck,
-Mike

**Comment by N3bbish** [comment]
Thanks for taking time out of your day to help. I am composing a post as we speak, but what do you mean when you say put the config in a code tag?

**Comment by mjp66** [comment]
In general: https://community.ui.com/questions/BuckeyeNets-link-farm/d58f154d-8dd7-48a3-aba1-5d35fb84c9d2
In particular (from the above link farm): https://help.ui.com/hc/en-us/articles/360012074414

**Comment by N3bbish** [comment]
Mike, I can’t tell you how much I appreciate your help. 

I’m going to do some testing tomorrow based on the community feedback. One thing I have noticed is that going to whatismyip.com shows that my public IP originates from Virginia, but I am in Northern California and I know that’s something you typically may see when using VPN. I also checked to see if my public IP was on any blacklists and it came up clean.

**Comment by mjp66** [comment]
Looks like this was solved in https://community.ui.com/questions/ER-X-Attempting-to-log-into-certain-websites-does-not-work-unless-I-use-VPN/96f0a27d-444f-4da3-bc72-4c31479083c1

**Comment by N3bbish** [comment]
Hi Mike—

Yes, you are correct. I found out yesterday that my community-provided internet has been going through changes. Original ISP was Gigamonster which was purchased by GigStream and is now being replaced by a local provider, AllStream Business. They have been changing about 200 IPs a day which explains why I am seeing traffic from two the different public subnets ranges. My original ER-X MAC is still locked in with the old ISP, but the changeover should be complete in another week or two so I will experiment with the MACs at the end of October. 

Thank you again for your help!
